version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: axe-core
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
    - 4.1.4
  - dependency-name: "@types/semver"
    versions:
    - 7.3.4
  - dependency-name: handlebars
    versions:
    - 4.7.6
